# syntax=docker/dockerfile:1

FROM ghcr.io/linuxserver/baseimage-alpine:arm32v7-3.17

# set version label
ARG BUILD_DATE
ARG VERSION
ARG SONARR_VERSION
LABEL build_version="Linuxserver.io version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="thespad"

# add local files
COPY root-armhf/ /

# ports and volumes
EXPOSE 8989

VOLUME /config