#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 \
            cd /app/sonarr/bin s6-setuidgid abc /app/sonarr/bin/Sonarr \
            -nobrowser -data=/config
else
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 \
            cd /app/sonarr/bin /app/sonarr/bin/Sonarr \
            -nobrowser -data=/config
fi
