#!/usr/bin/with-contenv bash
# shellcheck shell=bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 8989" \
        cd /app/sonarr/bin s6-setuidgid abc mono --debug Sonarr.exe \
        -nobrowser -data=/config
