#!/usr/bin/with-contenv bash
# shellcheck shell=bash

cat <<-EOF
    ********************************************************
    ********************************************************
    *                                                      *
    *                         !!!!                         *
    *          This Sonarr image does not support          *
    *   32 bit ARM due to lack of available OS packages    *
    *                                                      *
    *                                                      *
    ********************************************************
    ********************************************************
EOF
