#!/usr/bin/with-contenv bash

# install preview version of sonarr
if [ ! -d "/opt/sonarr" ]; then
 mkdir -p /opt/sonarr && \
 curl -o \
 /tmp/sonarr.tar.gz -L \
        "https://download.sonarr.tv/v2/phantom/latest/NzbDrone.phantom.tar.gz" && \
 tar xf \
 /tmp/sonarr.tar.gz -C \
        /opt/sonarr --strip-components=1 && \
rm /tmp/*.tar.gz
fi

# cleanup pid if it exists
[[ -e /config/nzbdrone.pid ]] && \
	rm -rf /config/nzbdrone.pid

# permissions
chown -R abc:abc \
	/opt/sonarr
